# Source: 
# - linuxserver/swag: https://docs.linuxserver.io/general/swag#creating-a-swag-container
# - Ansible Docker: https://docs.ansible.com/ansible/latest/modules/docker_container_module.html

---
- hosts: blogserver
  become: true
  vars_files:
    - "{{playbook_dir}}/../config_vars.yaml"

  tasks:
    - name: Start swag container with healthstatus
      docker_container:
        name: linuxserver-swag
        image: linuxserver/swag
        capabilities:
          - "NET_ADMIN"
        env:
            PUID: "1000"
            PGID: "1000"
            TZ: "Europe/Berlin"
            URL: "{{website_url}}"
            SUBDOMAINS: "www,"
            VALIDATION: "http"
            EMAIL: "{{website_email}}"
            DHLEVEL: "2048"
            STAGING: "false"
        exposed_ports:
            - "443:443"
            - "80:80"
        volumes:
            /etc/blogserver/config:/config
        state: started
        restart_policy: "unless-stopped" 
        network_mode: "host"
        healthcheck:
          # Check if nginx server is healthy by curl'ing the server.
          # If this fails or timeouts, the healthcheck fails.
          test: ["CMD", "curl", "--fail", "https://{{website_url}}"]
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 30s
